var top_query
= 'query {'
+    'viewer {'
+        'libraryEntries (states: WATCHING) {'
+            'nodes {'
+				'work{'
+                    'id,'
+                    'annictId,'
+                    'seasonName,'
+                    'seasonYear,'
+                    'title,'
+                    'officialSiteUrl,'
+                   'media,'
+                    'episodesCount,'
+                   'noEpisodes,'
+                    'image{'
+                       'recommendedImageUrl'
+				    '},'
+			    '}'
+                'nextEpisode{'
+                    'numberText,'
+                    'title,'
+                    'viewerDidTrack,'
+                    'id,'
+                    'annictId,'
+			    '}'
+			    'nextProgram{'
+			        'startedAt,'
+			        'channel{'
+				        'annictId,'
+				        'name,'
+			        '}'
+	    	    '}'
+            '}'
+        '}'
+    '}'
+'}'