var query
= 'query {'
+    'viewer {'
+        'works(state: WATCHING) {'
+              'nodes {'
+                'id,'
+                'annictId,'
+                'seasonName,'
+                'seasonYear,'
+                'title,'
+                'officialSiteUrl,'
+                'media,'
+                'episodesCount,'
+                'noEpisodes,'
+                  'image{'
+                    'recommendedImageUrl,'
+                    'facebookOgImageUrl'
+                '}'
+                'episodes(orderBy: {'
+                    'direction: ASC, field: SORT_NUMBER'
+                '}) {'
+                      'nodes {'
+                        'numberText,'
+                        'title,'
+                        'viewerDidTrack,'
+                        'id,'
+                        'annictId,'
+                    '}'
+                '}'
+            '}'
+        '}'
+    '}'
+'}'